# Form implementation generated from reading ui file 'add_regex.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from aqt.qt import (
    QCoreApplication,
    QDialogButtonBox,
    QListWidget,
    QListWidgetItem,
    QMetaObject,
    QRect,
    Qt,
)


class Ui_add_regex(object):
    def setupUi(self, add_regex):
        add_regex.setObjectName("add_regex")
        add_regex.resize(231, 221)
        self.buttonBox = QDialogButtonBox(parent=add_regex)
        self.buttonBox.setGeometry(QRect(10, 190, 211, 32))
        self.buttonBox.setOrientation(Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(
            QDialogButtonBox.StandardButton.Cancel | QDialogButtonBox.StandardButton.Ok
        )
        self.buttonBox.setObjectName("buttonBox")
        self.listWidget = QListWidget(parent=add_regex)
        self.listWidget.setGeometry(QRect(10, 10, 211, 181))
        self.listWidget.setObjectName("listWidget")
        item = QListWidgetItem()
        self.listWidget.addItem(item)
        item = QListWidgetItem()
        self.listWidget.addItem(item)
        item = QListWidgetItem()
        self.listWidget.addItem(item)
        item = QListWidgetItem()
        self.listWidget.addItem(item)
        item = QListWidgetItem()
        self.listWidget.addItem(item)
        item = QListWidgetItem()
        self.listWidget.addItem(item)
        item = QListWidgetItem()
        self.listWidget.addItem(item)

        self.retranslateUi(add_regex)
        self.buttonBox.accepted.connect(add_regex.accept)  # type: ignore
        self.buttonBox.rejected.connect(add_regex.reject)  # type: ignore
        QMetaObject.connectSlotsByName(add_regex)

    def retranslateUi(self, add_regex):
        _translate = QCoreApplication.translate
        add_regex.setWindowTitle(_translate("add_regex", "Add regex"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("add_regex", "Custom"))
        item = self.listWidget.item(1)
        item.setText(_translate("add_regex", "Redirect queries"))
        item = self.listWidget.item(2)
        item.setText(_translate("add_regex", "Remove element"))
        item = self.listWidget.item(3)
        item.setText(_translate("add_regex", "Remove empty elements"))
        item = self.listWidget.item(4)
        item.setText(_translate("add_regex", "Remove styles"))
        item = self.listWidget.item(5)
        item.setText(_translate("add_regex", "Remove tag"))
        item = self.listWidget.item(6)
        item.setText(_translate("add_regex", "Trim leading spaces"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
