# Form implementation generated from reading ui file 'regex_edit.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from aqt.qt import (
    QLabel,
    QLineEdit,
    QSize,
    QRect,
    QIcon,
    QToolButton,
    QPixmap,
    QCoreApplication,
    QMetaObject,
    QWidget,
)
from .. import resources  # noqa: F401


class Ui_regex_edit(QWidget):
    def setupUi(self, regex_edit):
        regex_edit.setObjectName("regex_edit")
        regex_edit.resize(421, 111)
        regex_edit.setStyleSheet("")
        self.name = QLabel(parent=regex_edit)
        self.name.setGeometry(QRect(10, 0, 311, 20))
        self.name.setObjectName("name")
        self.pattern_label = QLabel(parent=regex_edit)
        self.pattern_label.setGeometry(QRect(10, 20, 181, 21))
        self.pattern_label.setObjectName("pattern_label")
        self.replacement_label = QLabel(parent=regex_edit)
        self.replacement_label.setGeometry(QRect(229, 20, 180, 21))
        self.replacement_label.setObjectName("replacement_label")
        self.replacement = QLineEdit(parent=regex_edit)
        self.replacement.setGeometry(QRect(228, 40, 180, 21))
        self.replacement.setObjectName("replacement")
        self.up = QToolButton(parent=regex_edit)
        self.up.setGeometry(QRect(340, 0, 20, 20))
        self.up.setStyleSheet("border: none; background: transparent;")
        icon = QIcon()
        icon.addPixmap(QPixmap(":/icons/up"), QIcon.Mode.Normal, QIcon.State.Off)
        self.up.setIcon(icon)
        self.up.setIconSize(QSize(16, 20))
        self.up.setObjectName("up")
        self.down = QToolButton(parent=regex_edit)
        self.down.setGeometry(QRect(365, 0, 20, 20))
        self.down.setStyleSheet("border: none; background: transparent;")
        icon1 = QIcon()
        icon1.addPixmap(QPixmap(":/icons/down"), QIcon.Mode.Normal, QIcon.State.Off)
        self.down.setIcon(icon1)
        self.down.setIconSize(QSize(16, 20))
        self.down.setObjectName("down")
        self.edit = QToolButton(parent=regex_edit)
        self.edit.setGeometry(QRect(390, 0, 20, 20))
        self.edit.setStyleSheet("border: none; background: transparent;")
        icon2 = QIcon()
        icon2.addPixmap(QPixmap(":/icons/edit"), QIcon.Mode.Normal, QIcon.State.Off)
        self.edit.setIcon(icon2)
        self.edit.setIconSize(QSize(16, 20))
        self.edit.setObjectName("edit")
        self.count = QLineEdit(parent=regex_edit)
        self.count.setGeometry(QRect(9, 80, 181, 21))
        self.count.setObjectName("count")
        self.count_label = QLabel(parent=regex_edit)
        self.count_label.setGeometry(QRect(10, 60, 181, 21))
        self.count_label.setObjectName("count_label")
        self.flags = QLineEdit(parent=regex_edit)
        self.flags.setGeometry(QRect(229, 80, 180, 21))
        self.flags.setObjectName("flags")
        self.flags_label = QLabel(parent=regex_edit)
        self.flags_label.setGeometry(QRect(230, 60, 180, 21))
        self.flags_label.setObjectName("flags_label")
        self.pattern = QLineEdit(parent=regex_edit)
        self.pattern.setGeometry(QRect(9, 40, 181, 21))
        self.pattern.setObjectName("pattern")

        self.retranslateUi(regex_edit)
        QMetaObject.connectSlotsByName(regex_edit)

    def retranslateUi(self, regex_edit):
        _translate = QCoreApplication.translate
        regex_edit.setWindowTitle(_translate("regex_edit", "Form"))
        self.name.setText(_translate("regex_edit", "Regex label"))
        self.pattern_label.setText(_translate("regex_edit", "Pattern"))
        self.replacement_label.setText(_translate("regex_edit", "Replacement"))
        self.count_label.setText(_translate("regex_edit", "Count"))
        self.flags_label.setText(_translate("regex_edit", "Flags"))
